const express = require('express')
const { protect, allowRoles } = require('../middleware/authMiddleware')
const c = require('../controllers/adminController')
const r = express.Router()
r.use(protect, allowRoles('admin'))
r.get('/stats', c.getStats)
r.get('/pharmacies', c.listPharmacies)
r.get('/pharmacies/pending', c.listPendingPharmacies)
r.get('/pharmacies/:id/license-image', c.servePharmacyLicense)
r.put('/pharmacies/:id/approve', c.approvePharmacy)
r.put('/pharmacies/:id/reject', c.rejectPharmacy)
r.get('/pharmacies-with-accounts', c.listPharmaciesWithAccounts)
r.get('/transactions', c.listAllTransactions)
r.get('/expired-alerts', c.listExpiredDrugAlerts)
r.put('/expired-alerts/:id/dismiss', c.dismissExpiredAlert)
r.get('/expired-medicines', c.listExpiredMedicines)
module.exports = r
