const express = require('express')
const { protect, allowRoles } = require('../middleware/authMiddleware')
const c = require('../controllers/adminController')
const r = express.Router()
r.use(protect, allowRoles('admin'))
r.get('/pharmacies/pending', c.listPendingPharmacies)
r.get('/pharmacies/:id/license-image', c.servePharmacyLicense)
r.put('/pharmacies/:id/approve', c.approvePharmacy)
r.put('/pharmacies/:id/reject', c.rejectPharmacy)
module.exports = r
