const express = require('express')
const c = require('../controllers/medicineController')
const { protect, allowRoles, requireApprovedPharmacy } = require('../middleware/authMiddleware')
const r = express.Router()
r.get('/', c.getMedicines)
r.get('/mine', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.getMine)
r.post('/', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.create)
r.put('/:id', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.update)
r.delete('/:id', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.remove)
module.exports = r
