const express = require('express')
const c = require('../controllers/orderController')
const { protect, allowRoles } = require('../middleware/authMiddleware')
const r = express.Router()
r.post('/', protect, allowRoles('customer'), c.createOrder)
r.get('/mine', protect, allowRoles('customer'), c.getMyOrders)
r.get('/pharmacy', protect, allowRoles('pharmacy'), c.getPharmacyOrders)
r.put('/:orderId/approve', protect, allowRoles('pharmacy'), c.approvePharmacyOrder)
r.put('/:orderId/reject', protect, allowRoles('pharmacy'), c.rejectPharmacyOrder)
r.put('/:orderId/decline', protect, allowRoles('pharmacy'), c.rejectPharmacyOrder)
module.exports = r
