const express = require('express')
const c = require('../controllers/orderController')
const { protect, allowRoles, requireApprovedPharmacy } = require('../middleware/authMiddleware')
const { uploadOrderImages } = require('../middleware/uploadMiddleware')
const r = express.Router()
r.post('/', protect, allowRoles('customer'), uploadOrderImages, c.createOrder)
r.post('/payment/chapa/verify', protect, allowRoles('customer'), c.verifyChapaPayment)
r.get('/mine', protect, allowRoles('customer'), c.getMyOrders)
r.get('/transactions', protect, allowRoles('customer'), c.listTransactions)
r.get('/pharmacy', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.getPharmacyOrders)
r.get('/pharmacy/transactions', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.listPharmacyTransactions)
r.delete('/:orderId', protect, allowRoles('customer'), c.cancelCustomerOrder)
r.put('/:orderId/approve', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.approvePharmacyOrder)
r.put('/:orderId/reject', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.rejectPharmacyOrder)
r.put('/:orderId/decline', protect, allowRoles('pharmacy'), requireApprovedPharmacy, c.rejectPharmacyOrder)
module.exports = r
